const strings = {
  EN:"EN",
  EN_LOGIN: "Log In",
  EN_WELCOME_TO_LOGIN: "Welcome to the login screen!",
  EN_User_Name_PLACEHOLDER: "User name",
  EN_PASSWORD_PLACEHOLDER: "Password",
  EN_Header_TEXT:"Welcome to our\nNew system",
  EN_CLIENT_LIST: "Client",
  EN_PLACE:"Campsite",
  EN_AMOUNT:"Amount",
  EN_CONVERT:"Convert",
  EN_MATERIAL:"Material",
  EN_TRACKING_NUMBER: "Tracking number",
  EN_SUBSTANCE:"Substances groups",
  EN_VARIANTS:"Variants",
  EN_INVENTORY_AMOUNT:"Inventory amount",
  EN_PICK:"Pick",
  EN_PICK_ITEMS:"Pick items",
  EN_LOGOUT:"Logout",

  DU:"DU",
  DU_LOGIN: "Anmelden",
  DU_WELCOME_TO_LOGIN: "Welcome to the login screen!",
  DU_User_Name_PLACEHOLDER: "Benutzer",
  DU_PASSWORD_PLACEHOLDER: "Passwort",
  DU_Header_TEXT:"Herzlich Willkommen\nSchrottlogistik-System",
  DU_CLIENT_LIST: "Mandant",
  DU_PLACE:"Lagerplatz",
  DU_AMOUNT:"Menge",
  DU_CONVERT:"Convert",
  DU_MATERIAL:"Stoff",
  DU_TRACKING_NUMBER: "Sendungsnummer",
  DU_SUBSTANCE:"Stoffgruppe",
  DU_VARIANTS:"Varianten",
  DU_INVENTORY_AMOUNT:"Inventarbetrag",
  DU_PICK:"wählen",
  DU_PICK_ITEMS:"Elemente auswählen",
  DU_LOGOUT:"Ausloggen"
};
export default strings;
